// <auto-generated />
namespace Przychodnia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class wizyta_RodzajWizyty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wizyta_RodzajWizyty));
        
        string IMigrationMetadata.Id
        {
            get { return "201811281947583_wizyta_RodzajWizyty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
